# Use the official Node.js image as the base image
FROM node:lts

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install & npm i -g @nestjs/cli & wait

# Copy the rest of the application files
COPY . .

# Expose the application port
EXPOSE 3000 9229

# Command to run the application
CMD ["npm", "run", "start:debug"]